### ISSUE TITLE
redmine 5.0.3 - not compatible

### ISSUE THREAD

**Issue by saint-hh** [jbbarth/redmine_refresh#13]
_redmine_base_deface_ is running with 5.0.3 in the latest version, but _redmine_refresh_ unfortuantely not. This is what I get:

`Could not spawn process for application /var/www/redmine: The application encountered the following error: cannot load such file -- redmine_refresh/version (LoadError)`

Please let me know if you need more information or if I could test something for you.

**Comment by nanego** [comment]
The plugin has been updated and is now compatible with Redmine 5.0 and 5.1
Please give it a try and let us know if you encounter any issues.
