### ISSUE TITLE
Is it possible to configure the interval?

### ISSUE THREAD

**Issue by ilario-gottardello** [jbbarth/redmine_refresh#4]
Hello, I see on the code that the 120 seconds are only a default, it should retrieve personalized intervals, but I can't find where to configure them.

**Comment by ilario-gottardello** [comment]
Oh, now I see, it's a parameter on the url. It will be very cool if it will be possible to add a parameter on the user personal configuration page!

**Comment by nanego** [comment]
Thanks to @d-baranov and this pull request (#5), this feature is now available.
