### ISSUE TITLE
Sorting of blocks in my page isn't working anymore

### ISSUE THREAD

**Issue by davidegiacometti** [jbbarth/redmine_refresh#7]
Hi!

After installing redmine_refresh, sorting of blocks in my page isn't working anymore.
I have tried to inspect the issue, it seems caused by deface and not related to the JS code.
- Redmine version: 3.4.5.stable
- Ruby version: 2.3.3
- Rails version: 4.2.8
- Redmine Refresh: 0.3.1

Thanks

**Comment by nanego** [comment]
Hi. Which plugins are you using except redmine_refresh?

**Comment by davidegiacometti** [comment]
I am doing the test ona Redmine installation with only redmine_base_deface and redmine_refresh installed. Are you able to reproduce the issue?

**Comment by nanego** [comment]
I managed to reproduce this issue.
It comes from the javascript_tag in this file "app/views/my/page.html.erb". This file is overridden by Deface but some characters seem not valid in the generated code. 
I have just pushed a quick fix in this commit b53398c9e8a0967f4e5bdbee3226a6080df5aa6c. Please update the plugin and confirm the error is gone.

**Comment by davidegiacometti** [comment]
The fix solved the issue.
I leave the issue opened in case you want to examine the problem and provide a better fix but feel free to close if you want.

Thank you
