### ISSUE TITLE
Using redmine_refresh plugin on other pages

### ISSUE THREAD

**Issue by fabianofm1975** [jbbarth/redmine_refresh#9]
Dear Jean,

Firstly, thanks for your plugin. It´s great!
I was wondering if its possible to add the refresh also the agile page, as I use the redmineup agile free plugin.
Your help would be much appreciated.

Regards,

Fabiano

**Comment by nanego** [comment]
We don't use the Agile plugin here.
If you are a Ruby developer, contributions to the plugin are welcome.
But this issue should probably be sent to RedmineUp developers, who are maintaining the Agile plugin.
I'm closing this issue for now.
